server:
  port: 18085
spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      server-addr: 192.168.136.160:8848
    #网关路由的配置
    gateway:
      routes:
        - id: mall-sso
          uri: lb://mall-sso
          predicates:
            - Path= /admin/login

        - id: mall-admin
          uri: lb://mall-admin
          predicates:
            - Path=
