server:
  port: 18085
spring:
  application:
    name: mall-gateway
  cloud:
    #nacos配置
    nacos:
      discovery:
        server-addr: 192.168.136.160:8848
    #网关路由配置
    gateway:
      routes:
        - id: mall-admin
          uri: lb://mall-admin
          predicates:
           - Path= /admin/**,/role/**,/brand/**,/aliyun/**,/productAttribute/**
          #filters: StripPrefix=1  # 前缀， 在当前路径匹配中表示去掉第一个前缀
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*" # 允许哪些网站的跨域请求
            #- "http://192.168.200.125"
            allowedMethods: # 允许的跨域ajax的请求方式
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
            allowedHeaders: "*" # 允许在请求中携带的头信息
            #allowCredentials: true # 是否允许携带cookie
            #maxAge: 360000 # 这次跨域检测的有效期