spring:
  application:
    name: mall-dubbo-db
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.160:8848
      config:
        server-addr: 192.168.136.160:8848
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///mall?useSSL=false
    username: root
    password: root

# dubbo配置
dubbo:
  registry:
    address: spring-cloud://localhost
  protocol:
    port: 20881
    name: dubbo
  scan:
    base-packages: com.mall.dubbo.api
# mp配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl